
--SELECT : 선택
--FROM : 대상
--ORDER BY: 정렬
--GROUP BY: 구릅정렬
--DESC : 역순정렬
--COUNT : 카운트
--AS COUNT : 수정렬
--UNION : 합집합 중복미포함
--UNION ALL :합집합 중복포함
--INTERSECT : 교집합
--MINUS : 차집합
--DELECT : 삭제
--UPDATE : 수정


-- 테이블 전체 조회
SELECT * FORM ANIMAL_INS

-- 역순 정렬
SELECT NAME, DATETIME 
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID DESC

-- 아픈 동물찾기
SELECT ANIMAL_ID,NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID

-- 어린동물 찾기 
SELECT ANIMAL_ID,NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION !='Aged' 
ORDER BY ANIMAL_ID

-- 최소값 구하기
SELECT DATETIME 
FROM ANIMAL_INS 
ORDER BY DATETIME LIMIT 1

-- NULL 값 구하기
SELECT ANIMAL_INS
FROM ANIMAL_INS
WHERE NAME IS NULL

-- 카운터 문
SELECT, COUNT(ANIMAL_TYPE) AS COUNT 
FROM ANIMAL_INS GROUP BY ANIMAL_TYPE 

-- 카운터 조건문
SELECT NAME, COUNT(NAME) AS COUNT
FROM  ANIMAL_INS 
GROUP BY NAME HAVING COUNT(NAME) >= 2 

-- 없어진 기록찾기 (두 테이블을 조인하고 비교)
SELECT A.ANIMAL_ID , A.NAME 
FROM ANIMAL_OUTS A LEFT JOIN ANIMAL_INS B 
ON A.ANIMAL_ID = B.ANIMAL_ID 
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.ANIMAL_ID

--잘못된 입력된 구조 INPUT OUTPUT 테이블 불러와서 매칭비교연산후에 처리
-- 코드를 입력하세요
SELECT ED1.ANIMAL_ID, ED1.NAME
FROM (
    SELECT A.ANIMAL_ID, A.NAME, A.DATETIME AS ATIME, B.DATETIME AS BTIME 
    FROM ANIMAL_INS A, ANIMAL_OUTS B
    WHERE A.ANIMAL_ID = B.ANIMAL_ID
    ) ED1
WHERE ED1.ATIME > ED1.BTIME
ORDER BY ED1.ATIME